---
version: '3'

services:
  mysql:
    image: docker.io/library/percona:8.0.22-13
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: bench
      MYSQL_USER: bench
      MYSQL_PASSWORD: bench
      DOMAIN_NAME: mysql.sysbench.test
    command: |
      --innodb-doublewrite=0
      --default-authentication-plugin=mysql_native_password
      --performance-schema-session-connect-attrs-size=4096

  proxysql:
    image: docker.io/proxysql/proxysql:2.0.17
    environment:
      DOMAIN_NAME: proxysql.sysbench.test
    volumes:
      - "./proxysql.cnf:/etc/proxysql.cnf"
    depends_on:
      - mysql

  haproxy:
    image: docker.io/library/haproxy:2.3
    environment:
      DOMAIN_NAME: haproxy.sysbench.test
    volumes:
      - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    depends_on:
      - mysql
